# conda env create --file environment.yml
name: manejo_de_rutas_
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - fs
  - jupyter
  - jupyterlab
  - pathlib
  - pip
  - pyprojroot
  - python=3.9
  - pip:
    - pyhere
    